/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegoguatemalaquetzal;

import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Manuel
 */
public class VistaTop extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTop.class.getName());

    JFreeChart grafica;

    /**
     * Creates new form VistaRanking
     */
    //constructor ya creado por la clase
    public VistaTop() {
        initComponents();
        //llamada al metodo que muestra la grafica en pantalla 
        mostrarGrafica();
    }
//metodo para crear la grafica 
    public void mostrarGrafica() {
       //controlador para obtener los datos de las partidas
        PartidaController pController = new PartidaController();
        String[][] datos = pController.datosGraficaPersonaje();
     //se guardan los datos para la grafica
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        //recorrer los datos para agregarlos 
        for (int i = 0; i < datos.length; i++) {
            String nombre = datos[i][0];
            int puntos = Integer.parseInt(datos[i][1]);
            dataset.setValue(puntos, "puntos", nombre);
        }
       //se crea la grafica de barras 
        grafica = ChartFactory.createBarChart(
                "top de personajes por puntos",
                "jugadores",
                "punteo total",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );

        //cambiar de color  a la grafica para darle mas estilo
        grafica.setBackgroundPaint(java.awt.Color.white);
        grafica.getCategoryPlot().setBackgroundPaint(new java.awt.Color(230, 230, 250));
        grafica.getCategoryPlot().getRenderer().setSeriesPaint(0, new java.awt.Color(0, 102, 204));
        //enviamos que en el panel se crea la grafica
        ChartPanel panel = new ChartPanel(grafica);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(500, 300));

        PnlGrafica.removeAll();
        PnlGrafica.setLayout(new BorderLayout());
        PnlGrafica.add(panel, BorderLayout.CENTER);
        PnlGrafica.revalidate();
        PnlGrafica.repaint();
    }
//metodo para generar un documento con el top de jugadores

    public void exportarPDF() {
        try {
            Document documento = new Document();

            PdfWriter.getInstance(
                    documento,
                    new FileOutputStream("TopJugadores.pdf")
            );

            documento.open();

            // crear imagen de la grafica en memoria (SIN archivo PNG)
            BufferedImage bufferedImage = grafica.createBufferedImage(500, 300);

            // convertir a bytes
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bufferedImage, "png", baos);

            // convertir a imagen de iText
            Image imagen = Image.getInstance(baos.toByteArray());

            // ajustar tamaño
            imagen.scaleToFit(500, 300);

            // agregar al PDF
            documento.add(imagen);
            documento.add(new Paragraph("\n"));

            // titulo del documento
            documento.add(new Paragraph("TOP DE JUGADORES\n\n"));
              //obtenemos los datos 
            PartidaController pc = new PartidaController();
            String[][] datos = pc.datosGraficaPersonaje();
                //recorrer datos y agregar al pdf
            for (int i = 0; i < datos.length; i++) {
                documento.add(new Paragraph(
                        datos[i][0] + " - " + datos[i][1] + " puntos"
                ));
            }
             //cerrar el documento
            documento.close();
           //mensaje de que se guardo el documento pdf
            JOptionPane.showMessageDialog(null, "PDF generado correctamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlGrafica = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PnlGraficaLayout = new javax.swing.GroupLayout(PnlGrafica);
        PnlGrafica.setLayout(PnlGraficaLayout);
        PnlGraficaLayout.setHorizontalGroup(
            PnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        PnlGraficaLayout.setVerticalGroup(
            PnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        btnSalir.setText("salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnExportar.setText("EXPORTAR PDF");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnExportar)
                        .addGap(76, 76, 76)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(PnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnExportar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        exportarPDF();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaTop().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlGrafica;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
